apiVersion: v1
kind: Service
metadata:
  name: otel-collector-svc
  labels:
    app: otel-collector
    {{- include "agentstack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.collector.service.type }}
  ports:
    - port: 4317
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 4318
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: otel-collector
    {{- include "agentstack.selectorLabels" . | nindent 4 }}
