apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ provider_deployment_name }}"
  labels:
    app: "{{ provider_app_label }}"
    managedBy: beeai-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ provider_app_label }}"
  template:
    metadata:
      labels:
        app: "{{ provider_app_label }}"
    spec:
      containers:
        - name: agent-container
          image: "{{ image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: HOME
              value: /tmp
          envFrom:
            - secretRef:
                name: "{{ provider_secret_name }}"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8000
            initialDelaySeconds: 1
            periodSeconds: 3
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /ping
              port: 8000
            initialDelaySeconds: 1
            periodSeconds: 3
            timeoutSeconds: 2
