{{- if .Values.localDockerRegistry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: beeai-platform-registry-secret
  labels:
    app: beeai-platform-registry
    {{- include "beeai-platform.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{- $registryConfig := dict "auths" (dict
    (printf "beeai-platform-registry-svc:%d" (.Values.localDockerRegistry.service.port | int)) (dict "auth" "" "username" "" "password" "" "insecure" true)
    (printf "beeai-platform-registry-svc.%s:%d" .Release.Namespace (.Values.localDockerRegistry.service.port | int)) (dict "auth" "" "username" "" "password" "" "insecure" true)
  ) }}
    {{ $registryConfig | toJson | b64enc }}
{{- end }}