{{- if .Values.localDockerRegistry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: agentstack-registry-secret
  labels:
    app: agentstack-registry
    {{- include "agentstack.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{- $registryConfig := dict "auths" (dict
    (printf "agentstack-registry-svc:%d" (.Values.localDockerRegistry.service.port | int)) (dict "auth" "" "username" "" "password" "" "insecure" true)
    (printf "agentstack-registry-svc.%s:%d" .Release.Namespace (.Values.localDockerRegistry.service.port | int)) (dict "auth" "" "username" "" "password" "" "insecure" true)
  ) }}
    {{ $registryConfig | toJson | b64enc }}
{{- end }}