# check

["beeai-web:check"]
depends = ["beeai-web:check:*"]

["beeai-web:check:next"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm next lint"
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx"]
outputs = { auto = true }

["beeai-web:check:prettier"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm prettier --log-level silent --check src"
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx", "src/**/*.html", "src/**/*.css", "src/**/*.scss"]
outputs = { auto = true }

["beeai-web:check:eslint"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm eslint src"
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx"]
outputs = { auto = true }

["beeai-web:check:tsc"]
depends = ["common:setup:pnpm", "beeai-web:check:next"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm tsc --noEmit -p tsconfig.json"
sources = ["src/**/*.ts", "src/**/*.tsx"]
outputs = { auto = true }

["beeai-web:check:stylelint"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm stylelint src/**/*.css src/**/*.scss"
sources = ["src/**/*.css", "src/**/*.scss"]
outputs = { auto = true }

# fix

["beeai-web:fix"]
depends = ["beeai-web:fix:*"]

["beeai-web:fix:prettier"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm prettier --log-level silent --write src"
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx", "src/**/*.html", "src/**/*.css", "src/**/*.scss"]
outputs = { auto = true }

["beeai-web:fix:eslint"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm eslint --fix src"
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx"]
outputs = { auto = true }

["beeai-web:fix:stylelint"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm stylelint --fix=lax src/**/*.css src/**/*.scss"
sources = ["src/**/*.css", "src/**/*.scss"]
outputs = { auto = true }

# run

["beeai-web:run"]
depends = ["beeai-web:build:nextjs"]
env.NODE_OPTIONS = "--no-experimental-global-navigator"
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm next start"

["beeai-web:run:dev"]
depends = ["common:setup:pnpm"]
env.NODE_OPTIONS = "--no-experimental-global-navigator"
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm next dev"

# build

["beeai-web:build"]
depends = ["beeai-web:build:*"]
dir = "{{config_root}}"
run = "docker build -t ghcr.io/i-am-bee/beeai-platform/beeai-web:local -f ./apps/beeai-web/Dockerfile --load ."

["beeai-web:build:nextjs"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
env.NODE_OPTIONS = "--no-experimental-global-navigator"
run = "pnpm next build"
sources = ["*.json", "*.js", "*.mjs", "*.ts", "public/**/*", "src/**/*"]
outputs = { auto = true }
