[tools]
python = "3.11"
nodejs = "22"
uv = "latest"
pnpm = "latest"

[settings]
experimental = true # for python.uv_venv_auto
python.uv_venv_auto = true
raw = true

[hooks]
postinstall = "{{ mise_bin }} setup"

# TASKS

[task_config]
includes = [
    "apps/beeai-cli/tasks.toml",
    "apps/beeai-server/tasks.toml",
    "apps/beeai-ui/tasks.toml",
    "docs/tasks.toml",
    "packages/acp-python-sdk/tasks.toml",
    "packages/acp-typescript-sdk/tasks.toml",
    "packages/beeai-sdk/tasks.toml",
]

## grouped tasks

[tasks."setup"]
depends = ["setup:*"]

[tasks."check"]
depends = ["*:check"]

[tasks."fix"]
depends = ["*:fix"]

[tasks."test"]
depends = ["*:test"]

## git hooks

[tasks."git-hooks:pre-commit"]
hide = true
depends = ["check"]

## repo setup

[tasks."setup:mise-local-toml"]
hide = true
dir = "{{config_root}}"
run = "test -f mise.local.toml || cp mise.local.toml-example mise.local.toml"
sources = ["mise.local.toml-example"]
outputs = { auto = true }

[tasks."setup:git-hooks"]
hide = true
dir = "{{config_root}}"
run = """
printf '#!/bin/sh\n{{ mise_bin }} run git-hooks:pre-commit' >.git/hooks/pre-commit && chmod +x .git/hooks/pre-commit
"""
sources = [".git/hooks/pre-commit"]
outputs = { auto = true }

[tasks."setup:pnpm"]
hide = true
dir = "{{config_root}}"
run = "pnpm install"
sources = ["pnpm-lock.yaml", "pnpm-workspace.yaml", "apps/*/package.json", "packages/*/package.json", "docs/package.json"]
outputs = { auto = true }

[tasks."setup:uv"]
hide = true
dir = "{{config_root}}"
run = "uv sync --all-extras"
sources = ["uv.lock", "pyproject.toml", "apps/*/pyproject.toml", "packages/*/pyproject.toml"]
outputs = { auto = true }
