[tools]
# runtime
"asdf:CrouchingMuppet/asdf-lima" = "1.2.1" # using lima from asdf since the aqua one fails to install in CI

# Python
uv = "0.9.5"

# Node.js
nodejs = "22"
pnpm = "10.15.1"

# Kubernetes
helm = "latest"
kubeconform = "latest"
"ubi:telepresenceio/telepresence" = "latest"

# misc
yq = "latest"
"pipx:toml-cli" = "latest"
fd = "latest"
"ubi:google/addlicense" = "latest"
gum = "latest"

[settings]
experimental = true # for python.uv_venv_auto
python.uv_venv_auto = true
raw = true
node.gpg_verify = false # tends to randomly fail; sha is checked by lockfile

[hooks]
postinstall = "{{ mise_bin }} setup"

[env]
UV_PYTHON_PREFERENCE = "only-managed"

[task_config]
includes = [
    "./tasks.toml",
    "helm/tasks.toml",
    "apps/beeai-cli/tasks.toml",
    "apps/agentstack-sdk-py/tasks.toml",
    "apps/beeai-server/tasks.toml",
    "apps/beeai-ui/tasks.toml",
    "apps/beeai-web/tasks.toml",
    "apps/agentstack-sdk-ts/tasks.toml",
    "docs/tasks.toml",
]
