[tools]
# runtime
"asdf:CrouchingMuppet/asdf-lima" = "1.1.1" # using lima from asdf since the aqua one fails to install in CI

# Python
python = "3.13"
uv = "0.7.19"

# Node.js
nodejs = "22"
pnpm = "9.9.0"

# Kubernetes
helm = "latest"
kubeconform = "latest"
"ubi:telepresenceio/telepresence" = "latest"

# misc
yq = "latest"
"pipx:toml-cli" = "latest"
fd = "latest"
"ubi:google/addlicense" = "latest"

[settings]
experimental = true # for python.uv_venv_auto
python.uv_venv_auto = true
raw = true
node.gpg_verify = false # tends to randomly fail; sha is checked by lockfile

[hooks]
postinstall = "{{ mise_bin }} setup"

# TASKS

[task_config]
includes = [
    "./tasks.toml",
    "helm/tasks.toml",
    "apps/beeai-cli/tasks.toml",
    "apps/beeai-server/tasks.toml",
    "apps/beeai-ui/tasks.toml",
    "apps/beeai-web/tasks.toml",
    "docs/tasks.toml",
]

