packages:
  - apps/beeai-ui
  - apps/beeai-web
  - apps/eslint-config
  - apps/prettier-config
  - apps/stylelint-config
  - docs

catalog:
  '@svgr/webpack': 8.1.0
  '@types/lodash': 4.17.20
  eslint: 9.36.0
  globals: 16.4.0
  lodash: 4.17.21
  prettier: 3.6.2
  sass-embedded: ^1.93.1
  stylelint: 16.24.0
  typescript: 5.9.2
