packages:
  - apps/agentstack-ui
  - apps/beeai-web
  - apps/lint-config
  - apps/agentstack-sdk-ts
  - docs

catalog:
  '@carbon/icons-react': ^11.67.0
  '@carbon/react': ^1.91.0
  '@svgr/webpack': ^8.1.0
  '@tanstack/react-query': ^5.90.2
  '@types/lodash': ^4.17.20
  '@types/node': ^22.18.6
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  clsx: ^2.1.1
  eslint: ^9.36.0
  lodash: ^4.17.21
  lottie-react: ^2.4.1
  next: 15.5.4
  prettier: ^3.6.2
  react: ^19.1.1
  react-dom: ^19.1.1
  sass-embedded: ^1.93.2
  stylelint: ^16.24.0
  typescript: ^5.9.2
  usehooks-ts: ^3.1.1
