packages:
  - apps/beeai-ui
  - apps/beeai-web
  - apps/prettier-config
  - apps/stylelint-config
  - docs

catalog:
  '@eslint/eslintrc': 3.3.1
  '@eslint/js': 9.36.0
  '@next/eslint-plugin-next': 15.5.3
  '@svgr/webpack': 8.1.0
  '@types/lodash': 4.17.20
  eslint: 9.36.0
  eslint-config-next: 15.5.3
  eslint-config-prettier: 10.1.8
  eslint-plugin-react-hooks: 5.2.0
  eslint-plugin-simple-import-sort: 12.1.1
  globals: 16.4.0
  lodash: 4.17.21
  prettier: 3.6.2
  sass-embedded: ^1.93.1
  stylelint: 16.24.0
  typescript: 5.9.2
  typescript-eslint: 8.44.1
