[tool.uv.workspace]
members = [
  "apps/beeai-cli",
  "apps/beeai-server",
  "packages/mcp-python-sdk",
  "examples/simple-agent",
  "examples/simple-tool", "packages/beeai-sdk",
]

[tool.ruff]
line-length = 120
