[tool.uv.workspace]
members = [
  "apps/beeai-cli",
  "apps/beeai-server",
  "packages/beeai-sdk",
  "packages/acp-python-sdk",
]

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.uv]
dev-dependencies = [
    "pyright>=1.1.391",
    "pytest>=8.3.4",
    "ruff>=0.8.5",
]
