"""empty message

Revision ID: 29762474b358
Revises: c69e8ad9a82a
Create Date: 2025-10-20 09:44:21.015314

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29762474b358"
down_revision: str | None = "c69e8ad9a82a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "a2a_request_contexts",
        sa.Column("context_id", sa.String(length=256), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("context_id"),
    )
    op.create_table(
        "a2a_request_tasks",
        sa.Column("task_id", sa.String(length=256), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("task_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("a2a_request_tasks")
    op.drop_table("a2a_request_contexts")
    # ### end Alembic commands ###
