kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: beeai-jwks
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.storage.storage_class }}
  volumeMode: Filesystem
