apiVersion: v1
kind: Service
metadata:
  name: beeai-platform-svc
  labels:
    app: beeai-platform-server
    {{- include "beeai-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: beeai-platform-server
    {{- include "beeai-platform.selectorLabels" . | nindent 4 }}
