apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "agentstack.fullname" . }}-rolebinding
  labels:
    {{- include "agentstack.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "agentstack.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "agentstack.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io