apiVersion: v1
kind: Secret
metadata:
  name: "agentstack-secret"
  labels:
    app: agentstack-server
    {{- include "agentstack.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if (empty .Values.encryptionKey) }}
  {{fail ".Values.encryptionKey is missing, please generate one using: python3 -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())'"}}
  {{- else }}
  encryptionKey: {{.Values.encryptionKey | b64enc | quote}}
  {{- end }}
  sqlConnection: {{ printf "postgresql+asyncpg://%s:%s@%s:%s/%s"
       (include "agentstack.databaseUser" .)
       (include "agentstack.databasePassword" .)
       (include "agentstack.databaseHost" .)
       (include "agentstack.databasePort" .)
       (include "agentstack.databaseName" .)
       | b64enc | quote
  }}
  {{- if and .Values.postgresql.enabled .Values.postgresql.auth.enablePostgresUser }}
  sqlConnectionSuperuser: {{ printf "postgresql+asyncpg://%s:%s@%s:%s/%s"
       (include "agentstack.databaseAdminUser" .)
       (include "agentstack.databaseAdminPassword" .)
       (include "agentstack.databaseHost" .)
       (include "agentstack.databasePort" .)
       (include "agentstack.databaseName" .)
       | b64enc | quote
  }}
  {{- end }}
  {{- if and .Values.auth.enabled .Values.auth.basic.enabled (empty .Values.auth.basic.adminPassword) }}
  {{fail ".Values.auth.basic.adminPassword is missing, please add password."}}
  {{- else }}
  adminPassword: {{ .Values.auth.basic.adminPassword | b64enc | quote }}
  {{ end }}
  {{- if and .Values.auth.enabled (empty .Values.auth.jwtSecretKey) }}
  {{fail ".Values.auth.jwtSecretKey is missing, please a secret key"}}
  {{- else }}
  jwtSecretKey: {{ .Values.auth.jwtSecretKey | b64enc | quote }}
  {{ end }}
  s3AccessKeyId: {{ include "agentstack.s3.accessKeyID" . | b64enc | quote }}
  s3AccessKeySecret: {{ include "agentstack.s3.accessKeySecret" . | b64enc | quote }}
  {{- if .Values.github.auths }}
  .githubconfigjson: {{ .Values.github | toJson | b64enc | quote }}
  {{- end }}
  {{- if .Values.providerBuilds.externalClusterExecutor.kubeconfig }}
  providerBuildExternalClusterKubeconfig: {{ .Values.providerBuilds.externalClusterExecutor.kubeconfig | b64enc | quote }}
  {{- end }}
  {{- if and (include "agentstack.databaseSslEnabled" .) .Values.externalDatabase.sslRootCert }}
  sslRootCert: {{ .Values.externalDatabase.sslRootCert | b64enc | quote }}
  {{- end }}
