# check

["beeai-ui:check"]
depends = ["beeai-ui:check:*"]

["beeai-ui:check:prettier"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-ui"
run = "pnpm prettier --log-level silent --check src"
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx", "src/**/*.html", "src/**/*.css", "src/**/*.scss"]
outputs = { auto = true }

["beeai-ui:check:eslint"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-ui"
run = "pnpm eslint src"
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx"]
outputs = { auto = true }

["beeai-ui:check:tsc"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-ui"
run = "pnpm tsc --noEmit -p tsconfig.json"
sources = ["src/**/*.ts", "src/**/*.tsx"]
outputs = { auto = true }

["beeai-ui:check:stylelint"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-ui"
run = "pnpm stylelint src/**/*.css src/**/*.scss"
sources = ["src/**/*.css", "src/**/*.scss"]
outputs = { auto = true }

# fix

["beeai-ui:fix"]
depends = ["beeai-ui:fix:*"]

["beeai-ui:fix:prettier"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-ui"
run = "pnpm prettier --log-level silent --write src"
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx", "src/**/*.html", "src/**/*.css", "src/**/*.scss"]
outputs = { auto = true }

["beeai-ui:fix:eslint"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-ui"
run = "pnpm eslint --fix src"
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx"]
outputs = { auto = true }

["beeai-ui:fix:stylelint"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-ui"
run = "pnpm stylelint --fix=lax src/**/*.css src/**/*.scss"
sources = ["src/**/*.css", "src/**/*.scss"]
outputs = { auto = true }

# run

["beeai-ui:run"]
depends = ["beeai-ui:build:nextjs"]
env.NODE_OPTIONS = "--no-experimental-global-navigator"
dir = "{{config_root}}/apps/beeai-ui"
run = "pnpm next start"

["beeai-ui:run:dev"]
depends = ["common:setup:pnpm"]
env.NODE_OPTIONS = "--no-experimental-global-navigator"
dir = "{{config_root}}/apps/beeai-ui"
run = "pnpm next dev"

# build

["beeai-ui:build"]
depends = ["beeai-ui:build:*"]
dir = "{{config_root}}"
run = "docker build -t ghcr.io/i-am-bee/beeai-platform/beeai-ui:local -f ./apps/beeai-ui/Dockerfile --load ."

["beeai-ui:build:nextjs"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-ui"
env.NODE_OPTIONS = "--no-experimental-global-navigator"
run = "pnpm next build"
sources = ["*.json", "*.js", "*.mjs", "*.ts", "public/**/*", "src/**/*"]
outputs = { auto = true }

# schema

["beeai-ui:schema:generate"]
dir = "{{config_root}}/apps/beeai-ui"
run = "pnpm openapi-typescript 'http://localhost:8333/api/v1/openapi.json' -o ./src/api/schema.d.ts --alphabetize"
