apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ provider_deployment_name }}"
  labels:
    app: "{{ provider_app_label }}"
    managedBy: agentstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ provider_app_label }}"
  template:
    metadata:
      labels:
        app: "{{ provider_app_label }}"
    spec:
      containers:
        - name: agent-container
          image: "{{ image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: HOME
              value: /tmp
          envFrom:
            - secretRef:
                name: "{{ provider_secret_name }}"
          startupProbe:
            httpGet:
              path: /.well-known/agent-card.json
              port: 8000
            initialDelaySeconds: 1
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /.well-known/agent-card.json
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 2
