# check

["acp-python-sdk:check"]
depends = ["acp-python-sdk:check:*"]

["acp-python-sdk:check:ruff-check"]
dir = "{{config_root}}/packages/acp-python-sdk"
run = "uv run ruff check --quiet"
sources = ["src/**/*.py"]
outputs = { auto = true }

["acp-python-sdk:check:ruff-format"]
dir = "{{config_root}}/packages/acp-python-sdk"
run = "uv run ruff format --quiet --check"
sources = ["src/**/*.py"]
outputs = { auto = true }

["acp-python-sdk:check:pyright"]
dir = "{{config_root}}/packages/acp-python-sdk"
run = "uv run pyright"
sources = ["src/**/*.py"]
outputs = { auto = true }

# fix

["acp-python-sdk:fix"]
depends = ["acp-python-sdk:fix:*"]

["acp-python-sdk:fix:ruff-check"]
dir = "{{config_root}}/packages/acp-python-sdk"
run = "uv run ruff check --quiet --fix"
sources = ["src/**/*.py"]
outputs = { auto = true }

["acp-python-sdk:fix:ruff-format"]
dir = "{{config_root}}/packages/acp-python-sdk"
run = "uv run ruff format --quiet"
sources = ["src/**/*.py"]
outputs = { auto = true }

# test

["acp-python-sdk:test"]
dir = "{{config_root}}/packages/acp-python-sdk"
run = "uv run pytest"

# build

["acp-python-sdk:build"]
dir = "{{config_root}}/packages/acp-python-sdk"
run = "uv build --out-dir dist"

# clean

["acp-python-sdk:clean"]
dir = "{{config_root}}/packages/acp-python-sdk"
run = "rm -rf dist"
