{{-  if .Values.ui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentstack-ui
  labels:
    app: agentstack-ui
    {{- include "agentstack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: agentstack-ui
      {{- include "agentstack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.ui.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: agentstack-ui
        {{- include "agentstack.labels" . | nindent 8 }}
        {{- with .Values.ui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "agentstack.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "agentstack.serviceAccountName" . }}
      {{- with .Values.ui.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: agentstack-ui
          {{- with .Values.ui.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8334
              protocol: TCP
          {{- with .Values.ui.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: API_URL
              value: "http://agentstack-svc:{{.Values.service.port}}"
            - name: FEATURE_FLAGS
              value: |
                {
                  "Providers": {{ .Values.providerBuilds.enabled }},
                  "Variables": {{ .Values.features.uiVariables }},
                  "ModelProviders": {{ .Values.features.uiModelProviders }},
                  "MCPOAuth": {{ .Values.features.uiMCPOauth }},
                  "MCP": {{ .Values.features.uiMCP }},
                  "LocalSetup": {{ .Values.features.localSetup }}
                }
            - name: TRUST_PROXY_HEADERS
              value: {{ .Values.trustProxyHeaders | quote }}
          {{- if and .Values.auth.enabled .Values.auth.oidc.enabled }}
            - name: NEXTAUTH_URL
              value: {{ .Values.auth.oidc.nextauth_url }}
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  key: authSecret
                  name: agentstack-next-auth
            - name: OIDC_ENABLED
              value: "true"
            - name: OIDC_PROVIDERS
              valueFrom:
                secretKeyRef:
                  key: providers.json
                  name: agentstack-oidc-providers
          {{- else}}
            - name: OIDC_ENABLED
              value: "false"
          {{- end }}
          volumeMounts:
            {{- with .Values.ui.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- with .Values.ui.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
