{{-  if .Values.oidc.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: oidc-providers
  labels:
    app.kubernetes.io/component: beeai-ui
    app: beeai-ui
stringData:
  providers.json: |
    {{- toJson .Values.oidc.nextauth_providers | nindent 4 -}}
{{- end }}