{{-  if .Values.ui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: agentstack-ui-svc
  labels:
    app: agentstack-ui
    {{- include "agentstack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (eq .Values.ui.service.type "NodePort") }}
      nodePort: {{ .Values.ui.service.nodePort }}
      {{- end }}
  selector:
    app: agentstack-ui
    {{- include "agentstack.selectorLabels" . | nindent 4 }}
{{- end }}