apiVersion: apps/v1
kind: Deployment
metadata:
  name: beeai-platform
  labels:
    app: beeai-platform-server
    {{- include "beeai-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: beeai-platform-server
      {{- include "beeai-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/providers: {{ include (print $.Template.BasePath "/config/providers.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/config/secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: beeai-platform-server
        {{- include "beeai-platform.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "beeai-platform.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: run-migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: "/app/"
          command: [ "migrate" ]
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: AUTH__DISABLE_AUTH
              value: "true"
            - name: PERSISTENCE__ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: beeai-platform-secret
                  key: encryptionKey
            - name: PERSISTENCE__DB_URL
              valueFrom:
                secretKeyRef:
                  key: sqlConnection
                  name: {{ include "beeai.databaseSecretName" . }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: FEATURE_FLAGS__UI__USER_NAVIGATION
              value: {{ .Values.features.uiNavigation | quote }}
            - name: AGENT_REGISTRY__SYNC_PERIOD_SEC
              value: "30"
            - name: AGENT_REGISTRY__LOCATIONS__FILE
              value: file:///app/config/registry.yaml
            {{- range $name, $location := .Values.externalRegistries }}
            - name: AGENT_REGISTRY__LOCATIONS__{{ $name | upper }}
              value: {{ $location }}
            {{- end }}
            - name: PERSISTENCE__ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: beeai-platform-secret
                  key: encryptionKey
            - name: PERSISTENCE__DB_URL
              valueFrom:
                secretKeyRef:
                  key: sqlConnection
                  name: {{ include "beeai.databaseSecretName" . }}
            - name: AUTH__ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminPassword
                  name: beeai-platform-secret
            {{- if not .Values.auth.enabled }}
            - name: AUTH__DISABLE_AUTH
              value: "true"
            {{- end }}
          volumeMounts:
            - name: beeai-platform-providers
              mountPath: /app/config
              readOnly: true
            {{- with .Values.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: beeai-platform-providers
          configMap:
            name: beeai-platform-providers-cm
        {{- with .Values.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
