{{- if .Values.seaweedfs.enabled }}
{{- if eq .Values.seaweedfs.s3.existingConfigSecret "beeai-seaweedfs-default-config-secret" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: beeai-seaweedfs-default-config-secret
  labels:
    app.kubernetes.io/component: seaweed-s3
    app: seaweedfs-secret
stringData:
  # this key must be an inline json config file
  seaweedfs_s3_config: '{"identities":[{"name":"anvAdmin","credentials":[{"accessKey":"{{ .Values.seaweedfs.auth.admin.accessKeyID }}","secretKey":"{{ .Values.seaweedfs.auth.admin.accessKeySecret }}"}],"actions":["Admin","Read","Write"]}]}'
{{- end }}
{{- end }}
