# check

["helm:check"]
depends = ["helm:check:*"]

["helm:check:lint"]
dir = "{{config_root}}/helm"
run = "helm lint beeai-platform --with-subcharts --strict"
sources = ["beeai-platform/**/*"]
outputs = { auto = true }

["helm:check:render"]
dir = "{{config_root}}/helm"
run = "helm template beeai-platform -f ../agent-registry.yaml | kubeconform -strict -summary"
sources = ["beeai-platform/**/*"]
outputs = { auto = true }

# build

["helm:build"]
depends = ["helm:build:*"]

["helm:build:beeai-platform"]
dir = "{{config_root}}/helm"
run = "helm package beeai-platform"
sources = ["beeai-platform/**/*"]
