apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: beeai-platform-api
spec:
  parentRefs:
  - name: beeai-gateway
    namespace: istio-system
  hostnames: ["beeai-platform.api.testing"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/v1
    backendRefs:
    - name: beeai-platform-svc 
      port: 8333
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: beeai-platform-ui
spec:
  parentRefs:
  - name: beeai-gateway
    namespace: istio-system
  hostnames: ["beeai-platform.testing", "beeai-platform.api.testing"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: beeai-platform-ui-svc
      port: 8334
