name: ACP Typescript SDK

on:
  push:
    tags:
      - "acp-v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm publish --access public
        working-directory: packages/mcp-typescript-sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true # https://github.com/pnpm/pnpm/issues/6435#issuecomment-1518397267
