name: ACP Python SDK

on:
  push:
    tags:
      - "acp-v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish-pypi:
    name: Publish on PyPI
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: mise acp-python-sdk:build
      - uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        with:
          packages-dir: packages/acp-python-sdk/dist
