name: ACP Python SDK

on:
  push:
    tags:
      - "acp*"

jobs:
  pypi-publish:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: mise acp-python-sdk:build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: packages/acp-python-sdk/dist
