name: ACP Typescript SDK

on:
  push:
    tags:
      - "acp*"
    branches:
      - main
  pull_request:
    paths:
      - "packages/acp-typescript-sdk/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./packages/acp-typescript-sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./packages/acp-typescript-sdk/package-lock.json

      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm run check

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/acp')
    environment: release
    needs: build

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./packages/acp-typescript-sdk/package-lock.json
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      # TODO: Add --provenance once the repo is public
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
