name: Agents

on:
  push:
    tags:
      - "agents-v*"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agent:
          - official/composition
          - community/aider-agent
          - community/autogen-agents
          - community/crewai-agents
          - community/gpt-researcher-agent
          - community/langgraph-agents

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./agents/${{ matrix.agent }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/${{ matrix.agent }}:${{ github.ref_name }},ghcr.io/${{ github.repository }}/${{ matrix.agent }}:latest
