name: Agents

on:
  push:
    tags:
      - "agents-v*"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agent:
          - official/sequential-workflow
          - official/agent-docs-creator
          - official/beeai-framework/content-judge
          - official/beeai-framework/chat
          - official/beeai-framework/podcast-creator
          - official/beeai-supervisor
          - community/aider
          - community/gpt-researcher
          - community/literature-review
          - community/marketing-strategy
          - community/ollama-deep-researcher
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Read agent manifest
        id: agent-manifest
        run: |
          AGENT_MANIFEST=$(cat ./agents/${{ matrix.agent }}/agent.yaml | base64 -w 0)
          echo "content=$AGENT_MANIFEST" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./agents/${{ matrix.agent }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/${{ matrix.agent }}:${{ github.ref_name }},ghcr.io/${{ github.repository }}/${{ matrix.agent }}:latest
          labels: |
            beeai.dev.agent.yaml=${{ steps.agent-manifest.outputs.content }}
