name: BeeAI CLI

on:
  push:
    tags:
      - "beeai-cli-v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish-pypi:
    name: Publish on PyPI
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: mise beeai-cli:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: apps/beeai-cli/dist
