name: Common

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Check & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mise run check
      - run: mise run test
