name: PR

permissions:
  contents: read

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      UV_FROZEN: true
      UV_PYTHON_PREFERENCE: only-system
      MISE_NODE_GPG_VERIFY: "False" # gpg is present on GitHub CI runners, but somewhat broken
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .venv # NOTE: we could alternatively cache ~/.cache/uv
          key: uv-venv-v1-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: uv-venv-v1-${{ runner.os }}-
      - uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: pnpm-store-v1-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-store-v1-${{ runner.os }}-
      - uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8
        with:
          version: 2025.2.6
      - run: mise check
      - run: mise test
