name: PR

permissions:
  contents: read

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: mise check
      - run: mise test
