name: beeai-sdk-test

permissions:
  contents: read

on:
  workflow_dispatch: { }
  pull_request:
    paths:
      - 'apps/beeai-sdk/**'
  push:
    branches:
      - main
    paths:
      - 'apps/beeai-sdk/**'
jobs:
  beeai-sdk-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Lima"
        uses: lima-vm/lima-actions/setup@v1
        id: lima-actions-setup
      - name: "Cache ~/.cache/lima"
        uses: actions/cache@v4
        with:
          path: ~/.cache/lima
          key: lima-${{ steps.lima-actions-setup.outputs.version }}
      - uses: ./.github/actions/setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mise run beeai-sdk:e2e-test
