name: BeeAI Web

on:
  push:
    branches:
      - main
    paths:
      - 'apps/beeai-web/**'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/beeai-web/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/beeai-web:${{ github.sha }},ghcr.io/${{ github.repository }}/beeai-web:latest

  deploy:
    needs: publish
    runs-on: [self-hosted]
    steps:
      - uses: azure/setup-kubectl@v4
      - run: kubectl set image deployment/beeai-web beeai-web=ghcr.io/${{ github.repository }}/beeai-web:${{ github.sha }} -n ${{ secrets.CLUSTER_NAMESPACE }}
      - run: kubectl rollout status deployment/beeai-web --timeout 5m -n ${{ secrets.CLUSTER_NAMESPACE }}
